/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValidGuardRouteImport } from './routes/valid-guard'
import { Route as IndexRouteImport } from './routes/index'

const ValidGuardRoute = ValidGuardRouteImport.update({
  id: '/valid-guard',
  path: '/valid-guard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/valid-guard': typeof ValidGuardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/valid-guard': typeof ValidGuardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/valid-guard': typeof ValidGuardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/valid-guard'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/valid-guard'
  id: '__root__' | '/' | '/valid-guard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ValidGuardRoute: typeof ValidGuardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/valid-guard': {
      id: '/valid-guard'
      path: '/valid-guard'
      fullPath: '/valid-guard'
      preLoaderRoute: typeof ValidGuardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ValidGuardRoute: ValidGuardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
